---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
- package-ecosystem: github-actions
  directory: /  # Location of package manifests
  schedule:
    interval: monthly
  labels:
    - "ci"
    - "github_actions"
    - "bot"
  groups:   # open a single pull-request for all GitHub actions updates
    github-actions:
      patterns:
      - '*'
  open-pull-requests-limit: 10
  target-branch: devel
  cooldown:
    default-days: 7

- package-ecosystem: uv
  directory: /  # Location of package manifests
  schedule:
    interval: monthly
  labels:
    - "ci"
    - "dependencies"
    - "bot"
  groups:
    python-dependencies:
      patterns:
      - '*'
  open-pull-requests-limit: 10
  target-branch: devel
  cooldown:
    default-days: 7

