target-version = "py312"
line-length = 100
src = ["src", "tests"]
exclude = [
    "*.egg-info",
    ".cache",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".mypy_cache",
    ".nox",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "_build",
    "adhoc",
    "build",
    "data", 
    "dist",
    "docs/source/conf.py",
    "notebooks",
    "venv",
    "wrk",
]

[lint]
select=["ALL"]
ignore=[
  "COM812",
  "D203",
  "D211",
  "D213",
  "PLE1205",
  "PLR2004",
]

[lint.per-file-ignores]
"benchmarks/*" = ["S101"]
"tests/*" = [
  "ANN",
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "PLR2004",
  "RUF001",
  "S101",
]
"tools/*" = ["T201", "INP001", "S603", "S607"]

[lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 15

[lint.flake8-annotations]
mypy-init-return = true  # skip return type for __init__() methods

[lint.flake8-pytest-style]
parametrize-names-type = "csv"

[lint.flake8-type-checking]
strict = true

# warning: The isort option `isort.split-on-trailing-comma` is incompatible
# with the formatter `format.skip-magic-trailing-comma=true` option.
# To avoid unexpected behavior, we recommend either setting `isort.split-on-trailing-comma=false`
# or `format.skip-magic-trailing-comma=false`.

[lint.isort]
known-first-party = ["src", "tests"]
known-third-party = ["mpl_toolkits", "matplotlib", "numpy", "scipy", "loguru", "tqdm", "dotenv"]
default-section = "third-party"
lines-between-types = 1
required-imports = ["from __future__ import annotations"]
case-sensitive = true
section-order = [
    "future",
    "typing",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
    "testing"
]

[lint.isort.sections]
"typing" = ["typing", "typing_extension"]
"testing" = ["tests"]

[lint.pydocstyle]
convention = "google" # Use Google-style docstrings.

[format]
docstring-code-format = true
