#!/usr/bin/env python3
"""Show current path, denoting not existing directories."""

import os

from pathlib import Path


def main() -> None:
    """Show current path, denoting not existing directories."""
    doesnt_exist_label = " <- doesn't exist"
    system_path = os.environ["PATH"].split(os.pathsep)

    for p in system_path:
        print(f"{p:80}{'' if Path(p).exists() else doesnt_exist_label}")


if __name__ == "__main__":
    main()
