#!/bin/bash

# shellcheck source=/home/dvp/.bash-functions.rc
. "$HOME"/.bash-functions.rc
# set -o nounset
# set -o errexit
# set -o verbose
# set -o xtrace

#
# Reset pyenv environment
#
# Args:
#    environment: optional, if not provided uses first package name
#    from underlying `src` directory (usually this is the only one)
#
reset() {
    local env="${1:-}"
    read -r -a pkgs <<< "$(ls -1 src)"
    local pkg=${pkgs[0]}
    local last_python="3.13.0"
    [[ -z "$env" ]] && env="${pkg//_/-}"
    echo "Installing package $pkg to environment $env with python $last_python."
    eval "$(pyenv init -)"
    pyenv local "$last_python"
    pyenv virtualenv-delete -f  "$env" && echo "Removed environment $env"
    pyenv virtualenv "$last_python" "$env" && echo "Created environment $env"
    pyenv local "$env"
    pyenv activate "$env"
    python --version
    python -m pip install --upgrade pip setuptools wheel
    poetry config --local virtualenvs.create false
    poetry env info
    poetry lock --no-update
    poetry install
    pyenv deactivate
    pyenv local "$env" "3.12.7" "3.11.10" "3.10.15"
    pyenv rehash
    pyenv activate "$env"
    python -c "import ${pkg}; print(${pkg}.__version__)" && success "Environment $env is reset"
}

reset  "$@"

# vim: set ts=4 sw=4 tw=92 ss=0 ft=sh et ai :
