#!/bin/bash

# set -exu

pyenv virtualenv-delete -f  mapstp
pyenv virtualenv 3.11.1 mapstp
eval "$(pyenv init -)"
pyenv shell mapstp  # poetry should see mapstp env
poetry install
pyenv shell --unset
pyenv rehash
mapstp --version


# vim: set ts=4 sw=4 tw=92 ss=0 ft=sh et ai :
