name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'bump:') &&
      !contains(github.event.head_commit.message, '[skip_ci]')
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: x64
    - name: Install nox
      run: pip install --constraint=.github/workflows/constraints.txt nox nox-poetry
    - name: Install poetry
      run: pip install --constraint=.github/workflows/constraints.txt poetry
    - name: Run pytest, coverage and upload results to codecov
      run: nox --sessions tests-3.9 codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
