name: Create Repository Labels

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - master
      - devel
    paths:
      - .github/labels.yml
      - .github/workflows/labeler.yml
  pull_request:
    paths:
      - .github/labels.yaml
      - .github/workflows/labeler.yml
  schedule:
    - cron: "0 0 * * TUE"

jobs:
  labeler:
    name: Sycnchronize repository labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.MCKIT_GITHUB_TOKEN }}
          skip-delete: true
          dry-run: ${{ github.event_name == 'pull_request' }}
          exclude: |
            help*
            *issue
