name: Release

env:
  PYTHON_VERSION: '3.10'

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - master

defaults:
  run:
    shell: bash

concurrency:
  group: ci-release-${{ github.ref }}-1
  cancel-in-progress: true


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 2    # need previous revision to define tag

      - name: Set up Python
        uses: actions/setup-python@v4.3.1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Fix pip version
        run: |
          pip install --constraint=.github/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pip install --constraint=.github/constraints.txt poetry
          poetry --version

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "::set-output name=sha::$(git rev-parse --verify --quiet HEAD^)"

      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@v2.0.3
        with:
          version-command: poetry version --short

      - name: Bump version for developmental release
        if: "! steps.check-version.outputs.tag"
        run: |
          poetry version patch &&
          version=$(poetry version --short) &&
          poetry version $version.dev.$(date +%s)

      - name: Build package
        run: |
          poetry build --ansi

      - name: Publish package on PyPI
        if: steps.check-version.outputs.tag
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

      - name: Publish package on TestPyPI
        if: "! steps.check-version.outputs.tag"
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish the release notes
        uses: release-drafter/release-drafter@v5.21.1
        with:
          publish: ${{ steps.check-version.outputs.tag != '' }}
          tag: ${{ steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.MCKIT_GITHUB_TOKEN }}
