name: Release

env:
  PYTHON_VERSION: '3.13'

on:
  workflow_dispatch:

  release:
    types: ["published"]

concurrency:
  group: ci-release-${{ github.ref }}-1
  cancel-in-progress: true


jobs:
  release:
    name: Build and publish release
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Check out the repository
        uses: actions/checkout@v4

      - name: 📦 Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
          cache-dependency-glob: |
            **/uv.lock
            **/pyproject.toml

      - name: 📦 Build package
        run: |
          uv build

      - name: 📤 Publish package on PyPI
        if: ${{ !github.event.act }} # skip during local actions testing
        run: uv publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
