name: TestPyPI

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
jobs:
  lint:
    name: "Code quality check"
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'bump:') &&
      !contains(github.event.head_commit.message, '[skip_ci]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64
      # - name: Checkout submodules
        # run: git submodule update --init --recursive --depth=1
      - name: Install pip
        run:  |
          set -e
          python -m ensurepip
          python -m pip install --constraint=.github/workflows/constraints.txt pip
      - name: Install nox
        run: pip install --constraint=.github/workflows/constraints.txt nox nox-poetry
      - name: Install poetry
        run: pip install --constraint=.github/workflows/constraints.txt poetry
      - name: Run nox tests
        run: nox --python 3.9
  build_wheels:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    needs: lint
    runs-on: "${{ matrix.os }}"
    if: |
      !startsWith(github.event.head_commit.message, 'bump:') &&
      !contains(github.event.head_commit.message, '[skip_ci]')
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # , macos-latest, windows-latest]
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
        architecture: x64
    - name: Install poetry
      run:  |
        set -e
        python -m ensurepip
        python -m pip install --constraint=.github/workflows/constraints.txt pip
        pip install --constraint=.github/workflows/constraints.txt poetry
    - run: |
        set -e
        poetry version patch
        version=$(poetry version --short)
        poetry version $version.dev$(date +%s)
    # - name: Checkout submodules
      # run: git submodule update --init --recursive --depth=1
    - run: poetry install --no-dev
    - name: Build wheel
      run:  poetry build -f wheel
    - name: Build sdist
      run:  poetry build -s sdist
      if:   matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'
    - name: GitHub Release wheels (deploy)
      if: (github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags'))
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.MCKIT_GITHUB_TOKEN }}
    - name: Publish to TestPyPI
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry publish -r testpypi -u __token__ -p ${{ secrets.TEST_PYPI_TOKEN }}
